version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - pip install -r requirements.txt
      - python cloudperception/HelloWorld_tst.py
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation package --template-file samTemplate.yaml --output-template-file outputSamTemplate.yaml --s3-bucket $ARTIFACT_S3_BUCKET
artifacts:
  files:
    - *.zip
      #- samTemplate.yaml
      #- outputSamTemplate.yaml
      #- HelloWorld.py
